#!/usr/bin/env bash 
# this script does a number of things, see Task 9 in the README.
touch /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid' SIGQUIT
while :
do
	echo "To infinity and beyond";
done