#!/usr/bin/env bash 
# this script displays a phrase indefinitely with a sleep 2 in between each iteration. It displays a different phrase when receiving a SIGTERRM signal
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond";
	sleep 2;
done